# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab_hall_effect_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(648, 403)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_current_I1 = QtWidgets.QLabel(Form)
        self.label_current_I1.setObjectName("label_current_I1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_current_I1)
        self.input_current_I1 = QtWidgets.QLineEdit(Form)
        self.input_current_I1.setObjectName("input_current_I1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_current_I1)
        self.label_current_I2 = QtWidgets.QLabel(Form)
        self.label_current_I2.setObjectName("label_current_I2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_current_I2)
        self.input_current_I2 = QtWidgets.QLineEdit(Form)
        self.input_current_I2.setObjectName("input_current_I2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_current_I2)
        self.horizontalLayout.addLayout(self.formLayout)
        self.start_button = QtWidgets.QPushButton(Form)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.result_label = QtWidgets.QLabel(Form)
        self.result_label.setObjectName("result_label")
        self.verticalLayout.addWidget(self.result_label)
        self.constants_label = QtWidgets.QLabel(Form)
        self.constants_label.setObjectName("constants_label")
        self.verticalLayout.addWidget(self.constants_label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Лабораторная работа: Исследование эффекта Холла в полупроводниках"))
        self.label_current_I1.setText(_translate("Form", "Ток ДХ (I1, мА):"))
        self.label_current_I2.setText(_translate("Form", "Ток ЭМ (I2, мА):"))
        self.start_button.setText(_translate("Form", "Начать эксперимент"))
        self.result_label.setText(_translate("Form", "Результаты эксперимента будут отображены здесь"))
        self.constants_label.setText(_translate("Form", "Постоянные значения установки:\n"
"                                    Коэффициент усиления операционного усилителя k = 100\n"
"                                    Начальная индукция магнитного поля сердечника B_n = 0.1 Тл\n"
"                                    Коэффициент пропорциональности a = 0.5\n"
"                                "))
