# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab_fraunhofer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_experiment_type = QtWidgets.QLabel(Form)
        self.label_experiment_type.setObjectName("label_experiment_type")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_experiment_type)
        self.experimentTypeLayout = QtWidgets.QVBoxLayout()
        self.experimentTypeLayout.setObjectName("experimentTypeLayout")
        self.dark_current_radio = QtWidgets.QRadioButton(Form)
        self.dark_current_radio.setChecked(True)
        self.dark_current_radio.setObjectName("dark_current_radio")
        self.experimentTypeLayout.addWidget(self.dark_current_radio)
        self.photo_current_radio = QtWidgets.QRadioButton(Form)
        self.photo_current_radio.setObjectName("photo_current_radio")
        self.experimentTypeLayout.addWidget(self.photo_current_radio)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.experimentTypeLayout)
        self.label_voltage = QtWidgets.QLabel(Form)
        self.label_voltage.setObjectName("label_voltage")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_voltage)
        self.voltage_input = QtWidgets.QLineEdit(Form)
        self.voltage_input.setObjectName("voltage_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.voltage_input)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.distance_slider = QtWidgets.QSlider(Form)
        self.distance_slider.setMinimum(5)
        self.distance_slider.setMaximum(50)
        self.distance_slider.setProperty("value", 20)
        self.distance_slider.setOrientation(QtCore.Qt.Horizontal)
        self.distance_slider.setObjectName("distance_slider")
        self.horizontalLayout_3.addWidget(self.distance_slider)
        self.distance_value_label = QtWidgets.QLabel(Form)
        self.distance_value_label.setObjectName("distance_value_label")
        self.horizontalLayout_3.addWidget(self.distance_value_label)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_distance = QtWidgets.QLabel(Form)
        self.label_distance.setObjectName("label_distance")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_distance)
        self.horizontalLayout.addLayout(self.formLayout)
        self.start_button = QtWidgets.QPushButton(Form)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.result_label = QtWidgets.QLabel(Form)
        self.result_label.setObjectName("result_label")
        self.horizontalLayout_4.addWidget(self.result_label)
        self.constants_label = QtWidgets.QLabel(Form)
        self.constants_label.setObjectName("constants_label")
        self.horizontalLayout_4.addWidget(self.constants_label)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Лабораторная работа : Исследование внутреннего фотоэффекта"))
        self.label_experiment_type.setText(_translate("Form", "Тип эксперимента:"))
        self.dark_current_radio.setText(_translate("Form", "Темновой ток"))
        self.photo_current_radio.setText(_translate("Form", "Фототок"))
        self.label_voltage.setText(_translate("Form", "Напряжение (В):"))
        self.distance_value_label.setText(_translate("Form", "20 см"))
        self.label_distance.setText(_translate("Form", "Расстояние до экрана (см):"))
        self.start_button.setText(_translate("Form", "Начать эксперимент"))
        self.result_label.setText(_translate("Form", "Результаты эксперимента будут отображены здесь"))
        self.constants_label.setText(_translate("Form", "Постоянные значения установки:\n"
"Длина волны λ = 650 нм\n"
"Освещенность: 500 лк"))
