# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab_fraunhofer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_experiment_type = QtWidgets.QLabel(Form)
        self.label_experiment_type.setObjectName("label_experiment_type")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_experiment_type)
        self.experiment_type_combo = QtWidgets.QComboBox(Form)
        self.experiment_type_combo.setObjectName("experiment_type_combo")
        self.experiment_type_combo.addItem("")
        self.experiment_type_combo.addItem("")
        self.experiment_type_combo.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.experiment_type_combo)
        self.label_angle = QtWidgets.QLabel(Form)
        self.label_angle.setObjectName("label_angle")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_angle)
        self.angle_input = QtWidgets.QLineEdit(Form)
        self.angle_input.setObjectName("angle_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.angle_input)
        self.horizontalLayout.addLayout(self.formLayout)
        self.start_button = QtWidgets.QPushButton(Form)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.constants_label = QtWidgets.QLabel(Form)
        self.constants_label.setObjectName("constants_label")
        self.verticalLayout.addWidget(self.constants_label)
        self.result_label = QtWidgets.QLabel(Form)
        self.result_label.setObjectName("result_label")
        self.verticalLayout.addWidget(self.result_label)
        self.graph_widget = QtWidgets.QWidget(Form)
        self.graph_widget.setObjectName("graph_widget")
        self.graph_layout = QtWidgets.QVBoxLayout(self.graph_widget)
        self.graph_layout.setObjectName("graph_layout")
        self.verticalLayout.addWidget(self.graph_widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Лабораторная работа: Дифракция Фраунгофера"))
        self.label_experiment_type.setText(_translate("Form", "Тип эксперимента:"))
        self.experiment_type_combo.setItemText(0, _translate("Form", "Одиночная щель"))
        self.experiment_type_combo.setItemText(1, _translate("Form", "Одномерная решетка"))
        self.experiment_type_combo.setItemText(2, _translate("Form", "Двумерная решетка"))
        self.label_angle.setText(_translate("Form", "Угол (градусы):"))
        self.start_button.setText(_translate("Form", "Начать эксперимент"))
        self.constants_label.setText(_translate("Form",
                                                "Постоянные значения установки:\\nДлина волны λ = 650 нм\\nРасстояние до экрана L = 200 см"))
        self.result_label.setText(
            _translate("Form", "Результаты эксперимента будут отображены здесь"))
